version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "12:00"
      timezone: "Asia/Tokyo"
    groups:
      github-actions-all:
        patterns:
          - "*"
