name: Lint GHA workflow files
on: workflow_call
jobs:
  lint:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Install gha-fix
        shell: bash
        run: |
          set -x
          VERSION=0.2.0
          SHA256_SUM=67308ee5d6d19a241cf5fd578ec6f8739054a9a46a7293c6e8160e0b618c8f4d
          curl --silent --show-error --fail --connect-timeout 3 --max-time 10 --retry 3 \
            --location --remote-name \
            "https://github.com/Finatext/gha-fix/releases/download/v${VERSION}/gha-fix_Linux_x86_64.tar.gz"
          echo "${SHA256_SUM} gha-fix_Linux_x86_64.tar.gz" | sha256sum -c
          tar --extract --gzip --file gha-fix_Linux_x86_64.tar.gz --verbose
          sudo install gha-fix /usr/local/bin/gha-fix

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ github.head_ref }}
          sparse-checkout: .github

      - name: Run gha-fix pin and capture diff
        id: pin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |
          set -x
          PIN_DIFF_FILE="$(mktemp)"
          echo "diff_file=${PIN_DIFF_FILE}" >> "${GITHUB_OUTPUT}"

          gha-fix pin --ignore-owners Finatext -l debug

          git diff > "${PIN_DIFF_FILE}"

          if [[ -s "${PIN_DIFF_FILE}" ]]; then
            echo "has_changes=true" >> "${GITHUB_OUTPUT}"
            cat "${PIN_DIFF_FILE}"
          else
            echo "has_changes=false" >> "${GITHUB_OUTPUT}"
          fi

          git reset --hard HEAD

      - name: Run gha-fix timeout and capture diff
        id: timeout
        shell: bash
        run: |
          set -x
          TIMEOUT_DIFF_FILE="$(mktemp)"
          echo "diff_file=${TIMEOUT_DIFF_FILE}" >> "${GITHUB_OUTPUT}"

          gha-fix timeout -l debug

          git diff > "${TIMEOUT_DIFF_FILE}"

          if [[ -s "${TIMEOUT_DIFF_FILE}" ]]; then
            echo "has_changes=true" >> "${GITHUB_OUTPUT}"
            cat "${TIMEOUT_DIFF_FILE}"
          else
            echo "has_changes=false" >> "${GITHUB_OUTPUT}"
          fi

          git reset --hard HEAD

      - name: Install reviewdog
        if: steps.pin.outputs.has_changes == 'true' || steps.timeout.outputs.has_changes == 'true'
        shell: bash
        run: |
          set -x
          VERSION=0.20.3
          TARGET=Linux_x86_64
          SHA256_SUM=2c634dbc00bd4a86e4d4c47029d2af9185fab06643a9df0ae10e7c4d644781b6
          curl --silent --show-error --fail --connect-timeout 3 --max-time 10 --retry 3 \
            --location --remote-name \
            "https://github.com/reviewdog/reviewdog/releases/download/v${VERSION}/reviewdog_${VERSION}_${TARGET}.tar.gz"
          echo "${SHA256_SUM} reviewdog_${VERSION}_${TARGET}.tar.gz" | sha256sum -c
          tar --extract --gzip --file "reviewdog_${VERSION}_${TARGET}.tar.gz" --verbose
          sudo install reviewdog /usr/local/bin/reviewdog

      - name: Report gha-fix pin suggestions with reviewdog
        if: steps.pin.outputs.has_changes == 'true'
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |
          set -x
          reviewdog -f=diff -f.diff.strip=1 -name="gha-fix pin" -reporter=github-pr-review -filter-mode=nofilter < ${{ steps.pin.outputs.diff_file }}

      - name: Report gha-fix timeout suggestions with reviewdog
        if: steps.timeout.outputs.has_changes == 'true'
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |
          set -x
          reviewdog -f=diff -f.diff.strip=1 -name="gha-fix timeout" -reporter=github-pr-review -tee -filter-mode=nofilter < ${{ steps.timeout.outputs.diff_file }}
