# Test diff
name: Auto fix for GHA workflow files
on: workflow_call
jobs:
  auto-fix:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          sparse-checkout: .github
          fetch-depth: 2 # we need history to get previous commit
      - name: Install pinact
        shell: bash
        run: |
          set -x
          VERSION=1.6.0
          TARGET=linux_amd64
          SHA256_SUM=5562dfae2b70b9a14ba6bac99c691bec0bff41951411c713b5ea3fdbd28fbcc1
          curl --silent --show-error --fail --connect-timeout 3 --max-time 10 --retry 3 \
            --location --remote-name \
            "https://github.com/suzuki-shunsuke/pinact/releases/download/v${VERSION}/pinact_${TARGET}.tar.gz"
          echo "${SHA256_SUM} pinact_${TARGET}.tar.gz" | sha256sum -c
          tar --extract --gzip --file "pinact_${TARGET}.tar.gz" --verbose
          sudo install pinact /usr/local/bin/pinact
      - name: Install ghatm
        shell: bash
        run: |
          set -x
          VERSION=0.3.4
          TARGET=linux_amd64
          SHA256_SUM=8724d5946f5f62defa01d17b5651629eb9ff47963f0d2114dd2da30c0bad7205
          curl --silent --show-error --fail --connect-timeout 3 --max-time 10 --retry 3 \
            --location --remote-name \
            "https://github.com/suzuki-shunsuke/ghatm/releases/download/v${VERSION}/ghatm_${TARGET}.tar.gz"
          echo "${SHA256_SUM} ghatm_${TARGET}.tar.gz" | sha256sum -c
          tar --extract --gzip --file "ghatm_${TARGET}.tar.gz" --verbose
          sudo install ghatm /usr/local/bin/ghatm
      - name: Run linters
        shell: bash
        run: |
          set -x
          # Run pinact to pin GitHub Action versions
          pinact run
          # Run ghatm to set timeout-minutes
          ghatm set --timeout-minutes 5
      - name: Run git diff
        id: diff
        run: git diff --name-only --exit-code
        continue-on-error: true
      - name: Commit and push if fmt changes code
        if: steps.diff.outcome == 'failure'
        env:
          URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -x
          message='gha-autofix: Auto fix GHA workflow files'
          prev_message="$(git log -1 --pretty=format:'%s')"

          if [ "${prev_message}" = "${message}" ]; then
            echo "Detect auto generated commit-push loop"
            exit 1
          else
            git config user.name github-actions[bot]
            # Use this email to show icon in commit view.
            git config user.email github-actions[bot]@users.noreply.github.com
            git add .
            git commit -m "${message}"
            git push

            gh pr comment --body 'Commits pushed by bot. Trigger CI jobs by "making this PR draft then ready-for-review again" or "pushing an empty commit" or "updating branch".' "${URL}"
          fi
